'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, post, put } from '@/services/api';
import { useAction } from '@/hooks/use-action';
import { useUser } from '@/components/shell';
import { PageHeading, Notice, Loading, Badge, Table, Field, categories } from '@/components/shared';
import { Button } from '@/components/ui/button';
import type { Row } from '@/types';
export function Rules(){
  const{data=[],isPending,error}=useQuery({queryKey:['rules'],queryFn:()=>api<Row[]>('/rules')});const action=useAction(),user=useUser();const[editing,setEditing]=useState<Row|null>(null);
  return <><PageHeading eyebrow="ENGINEERING KNOWLEDGE" title="Engineering rules" description="Versioned, category-specific engineering constraints. Critical conflicts always block identity."/><Notice {...action}/><Notice error={error?.message}/>{user.role==='ADMIN'&&<section className="panel"><h2>{editing?'Edit rule · new version':'Create a category rule'}</h2><form key={editing?.id||'new'} onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const body={category:f.category,attribute_name:f.attribute_name,rule_type:f.rule_type,severity:f.severity,is_active:f.is_active==='on',rule_definition:{tolerance:Number(f.tolerance)}};const r=await action.run(()=>editing?put(`/rules/${editing.id}`,body):post('/rules',body),'Rule saved. Existing recommendations must be rerun before approval.');if(r)setEditing(null);}}><div className="form-grid"><Field title="Category"><input list="rule-categories" name="category" required defaultValue={editing?.category||'Valves'} readOnly={!!editing}/><datalist id="rule-categories">{categories.map(c=><option key={c}>{c}</option>)}</datalist></Field><Field title="Attribute name"><input name="attribute_name" required placeholder="pressure_class" defaultValue={editing?.attribute_name} readOnly={!!editing}/></Field><Field title="Comparison"><select name="rule_type" defaultValue={editing?.rule_type||'EXACT'}><option>EXACT</option><option>NUMERIC</option></select></Field><Field title="Severity"><select name="severity" defaultValue={editing?.severity||'CRITICAL'}><option>CRITICAL</option><option>IMPORTANT</option><option>NON_CRITICAL</option></select></Field><Field title="Numeric tolerance (canonical units)"><input name="tolerance" type="number" min="0" step="any" defaultValue={editing?.rule_definition?.tolerance||0}/></Field><label className="checkbox"><input type="checkbox" name="is_active" defaultChecked={editing?editing.is_active:true}/>Enabled</label></div><div className="button-row"><Button disabled={action.busy}>Save rule version</Button>{editing&&<Button type="button" variant="outline" onClick={()=>setEditing(null)}>Cancel edit</Button>}</div></form></section>}<section className="panel">{isPending?<Loading/>:<Table headers={['Category','Attribute','Rule','Severity','Tolerance','Version','Status','']}>{data.map(r=><tr key={r.id}><td>{r.category}</td><td className="mono">{r.attribute_name}</td><td>{r.rule_type}</td><td><Badge value={r.severity}/></td><td>{r.rule_definition.tolerance||0}</td><td>v{r.version}</td><td>{r.is_active?'Enabled':'Disabled'}</td><td>{user.role==='ADMIN'&&<Button size="sm" variant="outline" onClick={()=>{setEditing(r);window.scrollTo({top:0,behavior:'smooth'});}}>Edit rule</Button>}</td></tr>)}</Table>}</section></>;
}
export function Users(){
  const user=useUser(),action=useAction();const{data=[],isPending,error}=useQuery({queryKey:['users'],queryFn:()=>api<Row[]>('/users'),enabled:user.role==='ADMIN'});
  if(user.role!=='ADMIN')return <Notice error="Only administrators can manage user access."/>;
  return <><PageHeading eyebrow="ACCESS GOVERNANCE" title="Users & access" description="Server-enforced roles, active-account checks and auditable access changes."/><Notice {...action}/><Notice error={error?.message}/><section className="panel"><h2>Create user</h2><form onSubmit={e=>{e.preventDefault();action.run(()=>post('/users',Object.fromEntries(new FormData(e.currentTarget))),'User created.');}}><div className="form-grid"><Field title="Name"><input name="name" required/></Field><Field title="Email"><input name="email" type="email" required/></Field><Field title="Initial password (12+ characters)"><input name="password" type="password" required minLength={12} autoComplete="new-password"/></Field><Field title="Role"><select name="role">{['VIEWER','DATA_STEWARD','ENGINEER','ADMIN'].map(r=><option key={r}>{r}</option>)}</select></Field></div><Button disabled={action.busy}>Create user</Button></form></section><section className="panel">{isPending?<Loading/>:<Table headers={['Name','Email','Role','Access','']}>{data.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td><select aria-label={`Role for ${u.email}`} value={u.role} disabled={u.id===user.id||action.busy} onChange={e=>action.run(()=>put(`/users/${u.id}`,{role:e.target.value,is_active:u.is_active}),'Role updated.')}>{['VIEWER','DATA_STEWARD','ENGINEER','ADMIN'].map(r=><option key={r}>{r}</option>)}</select></td><td><Badge value={u.is_active?'ACTIVE':'DISABLED'}/></td><td><Button size="sm" variant="outline" disabled={u.id===user.id||action.busy} onClick={()=>action.run(()=>put(`/users/${u.id}`,{role:u.role,is_active:!u.is_active}),'Access updated.')}>{u.is_active?'Deactivate':'Activate'}</Button></td></tr>)}</Table>}</section></>;
}
export function Settings(){
  const{data,isPending,error}=useQuery({queryKey:['settings'],queryFn:()=>api('/settings')});const action=useAction(),user=useUser();
  if(isPending)return <Loading/>;if(error)return <Notice error={error.message}/>;
  return <><PageHeading eyebrow="PLATFORM CONFIGURATION" title="Settings & knowledge dictionary" description="Explicit terminology mappings enrich source data without inventing missing specifications."/><Notice {...action}/><section className="panel"><h2>Processing providers</h2><dl><dt>Embeddings</dt><dd>{data.embedding_provider}</dd><dt>Attribute extraction</dt><dd>{data.extraction_provider}</dd><dt>Publish & sync</dt><dd>{data.erp_sync}</dd><dt>Upload limit</dt><dd>{data.max_upload_mb} MB per file</dd></dl><p className="muted">Provider selection is configured on the backend through environment variables. No API secrets are exposed here.</p></section>{user.role==='ADMIN'&&<section className="panel"><h2>Add or update terminology</h2><form onSubmit={e=>{e.preventDefault();action.run(()=>post('/settings/dictionary',Object.fromEntries(new FormData(e.currentTarget))),'Dictionary version saved. Run enrichment to apply it to unverified records.');}}><div className="form-grid"><Field title="Source term"><input name="term" required placeholder="CS"/></Field><Field title="Expansion"><input name="expansion" required placeholder="Carbon Steel"/></Field><Field title="Kind"><select name="kind"><option>ABBREVIATION</option><option>SYNONYM</option><option>STANDARD</option><option>OEM</option></select></Field><Field title="Category scope"><select name="category"><option value="*">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></Field></div><Button disabled={action.busy}>Save terminology mapping</Button></form></section>}<section className="panel"><h2>Engineering dictionary</h2><Table headers={['Source term','Expansion','Kind','Category scope','Version']}>{data.dictionary.map((d:any)=><tr key={d.id}><td className="mono">{d.term}</td><td>{d.expansion}</td><td>{d.kind}</td><td>{d.category}</td><td>v{d.version}</td></tr>)}</Table></section></>;
}
